name: Census Data Exploration ML Project

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest flake8
          # if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install -r ./DevOps_Proj3_v1/requirements.txt

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ASIAZYKPQJWLMGXFKZRQ
          aws-secret-access-key: k2xH41kKWTseFcjwvmr9qL8a6sSn5THiuzNZWT/7
          aws-session-token: IQoJb3JpZ2luX2VjEKL//////////wEaDmFwLXNvdXRoZWFzdC0yIkYwRAIgAd8bUJbxhxLTfQhkZe/vcwn17nvqxrcWdVqn79El89kCIGH7ZkfSsXlUZEkZAYX3vRS//72jJJYJ8iqxQeU1czglKp4DCIv//////////wEQABoMNjcwNzE4NTEyNTM0IgzjfE/2r5BUUFv240wq8gKYmdS0ZXxsBPw19laQvLSJft9X5Bjes+Fr3JsemtbIgN9DCO6WmYu3ZUdvYxy31YDwsMo1ukSOqcnpC0ZHvYtc1wtthabjdKQP+NsWQLGVRf2W+ygauZe9i93P7gw0BVLYXlHFVe0iqkrgH2RGaJ7LL3rhKRWrdfpLHeS3+TFBngyzGlFHfooOe8Dmrr/KrWB7UxiUNX2QBaFDL5jQIHxSfJudg2kQra1WtlsF8oOayZhyIm8knEWYQFp5rDYagAIOWEHVVOwCuMs5xjvTG39ICERUHeMAQHjLyzZqtUlH68gfU1Obg6K4nRVjthdwUsTv/fliJ0SEN4w0F0pl0JyDnGhMO1HyGAF4hp6ynR9uTqB54DG1wRvZmh0K01kdyMWCasFY7g2u2a4PiRtz4KR4uLrPIDV1BRwpBzttzBcJ7OdWW+Qm90u001ieJ5GIrEXjMua+Tc+4+Se4mPPnYVkENMASQ9nnqBAVj7uw3IHY0WJoMP7vt5QGOqcBtk8DLN9I9PtTyzIcQ1HnckLwGjPDvx1dw1wAxkNYB0Z6dPN6F1tAdi4TtwyH60XYhxAE2RVztuqsRYoVUP/RweO1GFCOtlM4+wXiBvM7VGuviIHYED2u/ElA0eJWeuwfRXeFWH8OhB74jEZ0H3HPwwLwGhDVNcXiyDURXmWLtQXVcixU3I7iERPmhC8tYlJFMYy1AmrXtlFOAua5e9DfIN23RR1blQ8=
          aws-region: ap-southeast-2
        
      - name: Setup DVC
        uses: iterative/setup-dvc@v1
      - name: Pull data from DVC
        run: dvc pull -r driveremote
        
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Test with pytest
        run: pytest
