name: Census Data Exploration ML Project

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest flake8
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ASIAZYKPQJWLFWWCTBEQ
          aws-secret-access-key: +XoSK0OGgg/9WMQ0OXpeKt4NavuIyg9sCvWG4zaL
          aws-session-token: IQoJb3JpZ2luX2VjEI3//////////wEaDmFwLXNvdXRoZWFzdC0yIkYwRAIgFjaGPvaA6O5XOcmkdlRXSJbarjopyWP3zZ6BT3/ib9kCIGPOv0JiIen/ZKSIccnmdK/7cNgNT4Y7X88wscA8od7LKpUDCHYQABoMNjcwNzE4NTEyNTM0Igy0M0CTligrA/NkFkkq8gKPloFTGsoM9UkVYVt78Xfqp8m4wxGS1f6udXGSpMN/cwQ+Ig3Xt/dfJKn7vCOnJTV1HCM4xKqcSVt4UQINg5uQiVHcw0CWu6+/nLvwvfhtF9xhdvb0tBWO1KC6Ga113FjuxrzzO9WPwwR9ucdY6NfYRnaapw1DoCeHKdNFkGDfihLtEDrFTgm+a4zgVNqxDc7x63T+UyP2gS+5oK8e0a1CZS1ghLjFKcpAzDCig0k23EhJnqPuM/jP4ghpjfntXQWgAqJe1xohBuuvybccdHw3uO6coI0efK8RMR5to79zmgoEbsgbcQG1k73WMxfDSph869Ykd0ZZ3PfByc+SMpkpBddqUpIgbP8mk7gKiO2XnvIFHDKch1oEEOFW0kVwBJS+FoPMQxrguhxweP+zRuuGd9/0ClhJEAmU75JFB6ihjbyr+N2/pNAD1e1vZin4B/J/8PkcQp2fZ8EKnDOczzkLWtBOOR6lggzoedhiMsAwVT5uMKSes5QGOqcBAcIYmPeOhikehJJQhaql4lWyy80pd1JoLS1fDm75RFV48jV8mXrqolJ4dEe1+C/FSXRfs8VsQubbE8qtyLXhSt6smivQx/W2HEpnOw2lbuUPcCZhXdeirg1UmT9Up/gbKfd3UmQCZazDy5Vefzs7tw6lmaICAiYP7t386zqVyg9WHZlzUSgKdTij8zou/54uNM9AIWGLJwzSJs+nlFz2CvTb4Prz6vE=
          aws-region: ap-southeast-2
        
      - name: Setup DVC
        uses: iterative/setup-dvc@v1
      - name: Pull data from DVC
        run: dvc pull -r driveremote
        
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
#       - name: Test with pytest
#         run: pytest
