name: Census Data Exploration ML Project

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest flake8
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ASIAZYKPQJWLGGXIQZVP
          aws-secret-access-key: aPG1yo8oHu+zTF6p1aRTRP5W/kF6qRCMcB3pENDR
          aws-session-token: IQoJb3JpZ2luX2VjEAkaDmFwLXNvdXRoZWFzdC0yIkYwRAIgC0QMNl9igzIKu2ysLSg5qBtl8E7+Ne/djhAoSBKYdzYCIAN9Uyq8WjEb+pi1cMwlBxo7rumWANdZUT43G0CN7QquKp4DCOL//////////wEQABoMNjcwNzE4NTEyNTM0Igw5Owmfsasx/xQMhgcq8gKpcWy2+d/+XCc2Pp+HggMnNmClkAUdblZUhysR1PvQDHCu3pubSX6OTuvov3ufco58cl5JsXODjmqmQw0oOahcJ3VpOTl+bjP6qzBZgB0gLSl60bEf2uiG72xKUSi3/OpEL6sBVsU9XeITyA2H9CFP2Vom36ibUV8776cG/ORH0mQf0bG2bsBBFMgvjbtkwm69S7QAzHI1EKGnMb1qKRNMKLEyYUt0tYXLe8FfNjYTcBSUpP8g1EnvmK1ekac6Ul4aQZryJLcl3KzLjs+HD8VFXuUQ8ihgJfgFbmu2tfyliRI3y+WSGwqZk9k2KXEFyIgtsLMUOH3Uhi4urIBBCfWYgkJTSFN8QLjPhCMegAg7s9OOKqPlFL5bJJyjjuOvm0azr1zrCcr3hvGOqScvnTEYkzYUJhXGnUrKot3ovV9kzvvecKMB6zzoFtZ7E27ddGEskJ1bCCmW8ClowEK5KV+wGFy2jo3UlIj7aFEjgtAKR72rMP6llpQGOqcBjVjhspSA9Iu6zMT/+tD7xqv9Z7WUsc6U916Qkzm/PxKrnY2hTfzhEQadQm6p0hUeMeaqrZSH5HSVeT5pJqj43/LnY4jysYLRO8kTEWnjm0Z3mx50rvMbU3pG3ZctoqehV4w4MHqZMcgyRaPvUO5T4ZY2GAukawI8qn2EbdmmLRBoEWT99o0SvB2+41NNN8aGpfIdlShq9RTzhXhcCREzPw8huXpkbL0=
          aws-region: ap-southeast-2
        
      - name: Setup DVC
        uses: iterative/setup-dvc@v1
      - name: Pull data from DVC
        run: dvc pull -r new_remote
        
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
#       - name: Test with pytest
#         run: pytest
