name: Census Data Exploration ML Project

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest flake8
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ASIAZYKPQJWLJ774BOOU
          aws-secret-access-key: HHW9ECRl6fhJ8B1rUs8or+8MwVLwLGIk3uOQIsX9
          aws-session-token: IQoJb3JpZ2luX2VjEJb//////////wEaDmFwLXNvdXRoZWFzdC0yIkcwRQIhAJEoX2P80rXfouZkpr9AB1PdQHez5dLcvZw5Sr9OAPf+AiB9Os+I+GGfeVJnM5LBfcxAMwx9cvWEjIlwQIqLFIPAZyqVAwh/EAAaDDY3MDcxODUxMjUzNCIMiBwmEkMApghdNkCyKvICQRZrjaYUQgRuyTuGhyS1SBtpSib9oFSBpLzoqBTz1V7Cr6FM0F6bLIA27umI1LK+40hnLOYbs3tfDyRZK3rSdOZ48reipJ4KeX3BG34+VpyWDl0BmZDiv3v/r7JRIVdy+NAuRcz35j5X3Q2vAnNtxFQAFEN6jWpCNmqgV5olRm9wnQOQOTKS+JLjaxHUze6MhRHbrvaKSTFZu0PyvYt+AatLc13zuVQK0KDnGXyhf0h8YXYBgetAApvRkB7CKcF5PHQI/qh7p9dwhXzCyLymS+aFTBJY4bpB/olBHTEjl6uAkg29cpFFC9ceYtAT9gT5rFxECuMHdxJI3JQzWUCzdMUY67u8Ix+BN2QTMn0QrKE4bjnR101L0PdYxKh+CoMqQEVSI4UvQJXy9cLWBwJ+beqwby6Ks01DIIGKH5av8T73JLaOOK37GNEf/+h/WlrgssREHy+nQjIDrMt/oKqVKrtfEHrFC0NFkpmxvMMfKKrpRTD/nLWUBjqmAdA4Bk+HaS6jZ2R/lm5obeiYCvgugd3xvrOnwgCW6X/fU5FvwNQQNnkrnomeGlaG4UF4se1JYrNui3lRmKjymqRyloe5a91yhKkqCtrrlZ2eIdalyRmipxjNcZ5KDvo35lCS7HEWja3LRRdKxc21yW1JH8OzroxojrtNNrDlk+vJmMNmAlQluAvmVS2Mlhh/jS2p3l91mE/8HybMncy9nUysdejLXVA=
          aws-region: ap-southeast-2
        
      - name: Setup DVC
        uses: iterative/setup-dvc@v1
      - name: Pull data from DVC
        run: dvc pull -r driveremote
        
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
#       - name: Test with pytest
#         run: pytest
