name: Census Data Exploration ML Project

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest flake8
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ASIAZYKPQJWLJXMLWQEJ
          aws-secret-access-key: rqxC3Hwgx5Z/PUCwx/eEJHMtGyEfA75nGsFj6+CH
          aws-session-token: IQoJb3JpZ2luX2VjEIX//////////wEaDmFwLXNvdXRoZWFzdC0yIkcwRQIhANc1Ftwpwr3/ZfOfnfjB4lFrxL1PcoNJrfR4UpE9iIZUAiAe3LLm5Sg9gGn63+rVtGqiKyiu9Y9PTOM3Ah2lwawOPiqVAwhuEAAaDDY3MDcxODUxMjUzNCIM49UyiIN7uKT7JmxOKvIC8IjxgV0dQ50kaC2J7v8sJsU/DWmHfxeRP70cXkY5P74riMzxYKsz84/rIl63uvC8MmHVw83TuHs2Tpe8OXxTOFFTk8WGlE9MqSjuFGNiF1/FHiDWAX07mpRIUBvPO9zw6oh4VnFrgFtzl2OnPmdZQDJDYrcPYO6pf9XZDRc1cIDtEHRRZ0ukxrM2/AiBSYQ2+7mwSNNYjagBjcnLszAOYnzy8VwCvlkJSRwYil0WiOsBkRvj/F3UatUuzND4/obMVQBCCGECoQ9wAN2Lat/74g4xWf+eYpYlr0ObCARGX3FStnN5s5cVibLL3nc/4aaAAYCumGv1A0ybOJ6hBSn5eFo40nlSiLcAGv6KxFnoRhG+WPhgj8Fh2SE5qTxJ7S0g49hSLIhUIcl0BPQJC4Vjz/TcllQ6VFL49DADujsYMY0HhmOs5D3MM2yUSP9jyn6l81i4Cgk5F4lL8A6tfqadXhTnAIJgiS+ux4K3sIU5s/FN+zChwrGUBjqmARQdj4Tp/EXyieN8lhts7j3BP7x1oMnmiLg+D0jA/SkfyDsYjO+RA35adx2JgKKoS89D+ufgXMeLUk6ePtFewcrPwGuJBCqRz9OVf7quCCZgzZ+5DQllbTyhpNjD+KUe0Zui5KKWxjms4NfNKQvk+Tw7LwGZU44jTd/+zereJpfS38wTYyOF+Prvy70AwmGuB+NHplNwKDrSAVLpgfcgzDPFBkFJxvE=
          aws-region: ap-southeast-2
        
      - name: Setup DVC
        uses: iterative/setup-dvc@v1
      - name: Pull data from DVC
        run: dvc pull -r driveremote
        
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
#       - name: Test with pytest
#         run: pytest
