name: Census Data Exploration ML Project

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest flake8
          # if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install -r ./DevOps_Proj3_v1/requirements.txt

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:

#           aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
#           aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
#           aws-session-token: ${{secrets.AWS_SESSION_TOKEN}}
          aws-access-key-id: ASIAZYKPQJWLNAEQGZQC
          aws-secret-access-key: pZxRe6XtbgWouf4mlXT5LkpgLcyguyKIdeb5Mc6T
          aws-session-token: IQoJb3JpZ2luX2VjEK///////////wEaDmFwLXNvdXRoZWFzdC0yIkcwRQIhAOlTOHkM3/FqzfXbAcjcdMoh+/h+/kNOBuFddxrJ97N1AiBabFwHCcjRXf1SU2tVT81pMJw9A1A6L4vV6pCZqXplHCqeAwiY//////////8BEAAaDDY3MDcxODUxMjUzNCIMuoqYXi8uCxKF72wkKvICqgtdaNJD850orxQRCn6IVBG05KagKXagHptSj6yx7mtoAOoq5sgsob2CD0WdapYXLqZvvlN93gXj+iweLmKFsWVCW0P21S6u29FKO2xhk3JfPMPQOWbU5FD5/vXxUQXH9GUnMmRLqs7CSsyNTW8j90Q3pNekIBOS3uF2kE0p98FHhPK88OuzZiL3E0U8ck9V979nh6uB0q1YRsF15YD7Q6zOaN/PLpq3eMzsmPI5ayI+ty4zlgIWzjmSWSx/trlHB8C/6bnuYcH9vP7TjQWX0OZ0qz6L0CULD26S7x10jvnXyp026u/RP0dOgxfQ0fVrkxz4r/rlL7FJ2Vbv0ja6pNDhMhPbTRqRos02VaqBkHMIc0n3YAvtsF6TVvx4wGPBZzXtvbxjvRU+y5pYA8LzFoJ32zZ6wRKDDX+6fHK4/WqTjQj+N1n4CaO7yLc5d+ASpeN9S4gc61HlmQMLkoHanpMJteofIE2WBkuvl64pIDwMbzCt4LqUBjqmAWLcqSUo0zAlTJJFyzB8RqKJBp6edhauTcJsF6U6ao3PBHC2qC3kQVudC1GRaLyqtLLev+ea9FsIAlpEeTJAVNBaJUZP5LKUd/RZ3Xn6TG/BYE6n3LlUkUTJGyNPCDz/WieAmW3niRwcY4P8UziVykqDvDf7yuoBKiMlsF96lKELhvcE+63SOjLE3MrtTHjEjmQepMXto7r03VgnbCJfx5mmfNtzCJk=

          aws-region: ap-southeast-2
        
      - name: Setup DVC
        uses: iterative/setup-dvc@v1
      - name: Pull data from DVC
        run: dvc pull -r driveremote
        
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Test with pytest
        run: pytest
