name: Census Data Exploration ML Project

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest flake8
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ASIAZYKPQJWLMFIRHOQD
          aws-secret-access-key: 4mO7Ff69b+GyaMaBaSU0OPbdwB4fdX6fynYUdtsy
          aws-session-token: IQoJb3JpZ2luX2VjEJz//////////wEaDmFwLXNvdXRoZWFzdC0yIkcwRQIhAM+KCh3tRGRpfqW9pCYXSS1L0eUntltYpJGCWUNRwAdDAiBrfVUK/f2WoMK2aiHC8QrSUzNmirglp5UQy010gIbihiqeAwiF//////////8BEAAaDDY3MDcxODUxMjUzNCIMrjJpQOKe6gHYVrN6KvICzdgfcuqPDzHNirqlZObTtwqmYu/5bwEylZbcVTFP7bMKhhmW4dvihwhCHFTPp/6/mmx63Hu2loLKG2kP6MVxoCmZEgrBoit4uq3k5XDcpFN7WUC4BKrfZi1nS24+COEGBguaRgf3cUIRCuxeE8PcuF/MBpOgQfvT8HYuEJNU4ZpEsz4kxKbrWKYzKkyZz8ytngckse3rAn96e1ZrwiYyzGmdQcR6TAPfQbClj+23tfn1HNlv+qxtazIZynk4nmcNqgmMClOEwFtm1ypn9BavcypnVCfwDD3S98LSJsfhd3Imwdj1P/BUWiXHYw73YkUaABF9aXymUo0une+e2jY41E1LhJFlpdVC5zaKbKTxCVtl6CGR/t8FtSClimw85g2P3ZLgxNSCZvb+n0aiapjuevDFNo3NzvAdVk7vK1smgdimFJkr8n+PCGmkYujncjEgFAKt9MJZUhY7hxPCTsa9zYZtGe/GAYgTNgaHGjVLNQH8LTD607aUBjqmARKoWDRD2SZcZ2paqnwOefi4KltRBRMhcBtWRUtvZz86X13PMpRJT2g99KCsoC49xiffAHrz4EaQLWjQBGQ8PMCidKIzentadHL3O6ksEEB8WLFOn0Nvosol99Sy51Cyk2Gzy/bpiXxc6W7Fs/YTgThn0NMqzaOK5kzU0oVdxRz9yQ1lh2Q5OYdBmBk8cYTBwkEUetQ9DvnxtSO1Ff1XWVhXP3bRpyI=
          aws-region: ap-southeast-2
        
      - name: Setup DVC
        uses: iterative/setup-dvc@v1
      - name: Pull data from DVC
        run: dvc pull -r driveremote
        
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
#       - name: Test with pytest
#         run: pytest
